---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: quorum2
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
